---
# tasks file for scripts

- name: Create scripts directory
  ansible.builtin.file:
    path: "{{ item.directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop: "{{ scripts }}"
  loop_control:
    label: "{{ item.directory }}"

- name: Place scripts
  ansible.builtin.template:
    src: script.sh.j2
    dest: "{{ item.directory }}/{{ item.name }}.sh"
    owner: root
    group: root
    mode: 0755
  loop: "{{ scripts }}"
  loop_control:
    label: "{{ item.name }}"
