---
# tasks file for ntp

- name: Install ntp packages
  ansible.builtin.dnf:
    name: "{{ ntp_packages }}"
    state: present

- name: Configure ntp
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "/etc/{{ ntp_conf }}"
    mode: 0644
  notify:
    - Restart ntp

- name: Configure timezone
  community.general.timezone:
    name: "{{ ntp_timezone }}"

- name: Start and enable ntp service
  ansible.builtin.service:
    name: "{{ ntp_service }}"
    state: started
    enabled: true
