---
# tasks file for repos

- name: Include apt.yml
  ansible.builtin.include_tasks:
    file: apt.yml
  when:
    - ansible_pkg_mgr in [ "apt" ]

- name: Include dnf.yml
  ansible.builtin.include_tasks:
    file: dnf.yml
  when:
    - ansible_pkg_mgr in [ "dnf", "dnf5", "yum" ]
