---
# handlers file for systemd

- name: Restart systemd-journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Unmask systemd-logind
  ansible.builtin.systemd:
    name: systemd-logind
    masked: false

- name: Restart systemd-logind
  ansible.builtin.service:
    name: systemd-logind
    state: restarted
