# Defaults file for aide

aide_package: "aide"

aide_db: /var/lib/aide/aide.db.gz
aide_db_new: /var/lib/aide/aide.db.new.gz

aide_init_command: "aide --init"

aide_conf_path: /etc/aide.conf

aide_cronjob_name: "Aide check"
aide_cron_min: "0"
aide_cron_hour: "12"
aide_cron_day: "*"
aide_cron_month: "*"
aide_cron_weekday: "*"
