---
# defaults file for aide

aide_cron_jobs:
  - name: AIDE check
    hour: "12"
    job: "aide --check | logger -t aide -p cron.info"
  - name: Move AIDE db files
    hour: "13"
    job: "mv -f /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz"
