---
# defaults file for ulimit

# Default domain for limits configuration file.
ulimit_domain: '*'

# Default limit type for limits configuration file.
ulimit_limit_type: soft

# The filepath of the limits configuration file.
ulimit_file: /etc/security/limits.conf

# Backup limits.conf when changes occur.
ulimit_backup: true

# Configurations for ulimit. Domain (defaults to 'ulimit_domain'), Type (defaults to 'ulimit_limit_type'), Limit Item, Value.
ulimit_configurations: []
#  - domain: root
#    type: hard
#    limit_item: nproc
#    value: 2048
