---
galaxy_info:
  author: itscturner
  role_name: lvm
  description: An ansible role to configure logical volumes.
  license: Apache-2.0
  min_ansible_version: "2.12"

  platforms:
    - name: RHEL
      versions:
        - "9"

  galaxy_tags:
    - lvm
    - storage
    - system

  dependencies: []
