---
# tasks file for epel

- name: Check if EPEL repo file exists
  ansible.builtin.stat:
    path: "{{ epel_repofile }}"
  register: epel_repofile_check

- name: Import EPEL GPG key
  ansible.builtin.rpm_key:
    key: "{{ epel_repo_gpg_key }}"
    state: present
    
- name: Install EPEL repo
  ansible.builtin.dnf:
    name: "{{ epel_repo_url }}"
    state: present
