---
# tasks file for hostname

- name: Ensure hostname package is installed
  ansible.builtin.dnf:
    name: hostname
    state: present

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  notify:
    - Reboot
    - Gather Facts
  when:
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
