---
# tasks file for helm

- name: Check if helm is installed
  ansible.builtin.stat:
    path: "{{ helm_bin_path }}"
  register: helm_install_check

- name: Check helm version
  ansible.builtin.shell:
    cmd: "{{ helm_bin_path }} version"
  register: helm_existing_version
  failed_when: false
  changed_when: false

- name: Download helm
  ansible.builtin.unarchive:
    src: "{{ helm_url }}/helm-{{ helm_version }}-{{ helm_platform }}-{{ helm_arch }}.tar.gz"
    dest: /tmp
    mode: 0755
    remote_src: true
  register: helm_download
  when:
    - not helm_install_check.stat.exists or helm_version not in helm_existing_version.stdout

- name: Copy helm binary
  ansible.builtin.copy:
    src: "/tmp/{{ helm_platform }}-{{ helm_arch }}/helm"
    dest: "{{ helm_bin_path }}"
    mode: 0755
    remote_src: true
  when: helm_download is changed
