---
# defaults file for rust

# Rust version.
# rust_version:

# Should rust be updated?
rust_update: false

# Rust dependenices.
rust_dependencies:
  # - cmake
  - curl
  # - gcc

# Where the rust installer will be downloaded to.
rust_installer_download_destination: /tmp/sh.rustup.rs

# Additional packages for rust.
rust_additional_packages:
  - ferris-says

#  
#rust_shell_profiles:
#  - .bash_profile
#  - .bashrc
#  - .zshrc
