---
# tasks file for aide

- name: Install aide
  ansible.builtin.dnf:
    name: aide
    state: present

- name: Initialize aide
  ansible.builtin.shell:
    cmd: "aide --init"
    creates: "{{ aide_db_new }}"
  notify:
    - Copy new aide database

- name: Schedule aide check
  ansible.builtin.cron:
    name: aide check
    job: aide --check
    special_time: daily
