---
# defaults file for systemd

# Select the target to boot into. "Graphical", "Multi-user" or "Rescue".
systemd_target: ""

# Options for coredump.conf. (Key, Value).
systemd_coredump: []

# Options for journald.conf. (Key, Value).
systemd_journald: []

# Options for logind.conf. (Key, Value).
systemd_logind: []

# Options for system.conf. (Key, Value).
systemd_system: []

# Options for user.conf. (Key, Value).
systemd_user: []
