---
# tasks file for password

- name: Template pwquality.conf
  ansible.builtin.template:
    src: pwquality.conf.j2
    dest: /etc/security/pwquality.conf
    owner: root
    group: root
    mode: 0644

- name: Enforce password policies in login.defs
  ansible.builtin.lineinfile:
    dest: "{{ password_logindefs_file }}"
    #####
    backup: yes
    state: present
    dest: '{{ password_expiration_file }}'
    regexp: '^{{ item.search }}'
    line: '{{ item.replace }}'
  with_items:
      - { search: 'PASS_MAX_DAYS', replace: 'PASS_MAX_DAYS  {{ password_passmaxdays }}' }
      - { search: 'PASS_MIN_DAYS', replace: 'PASS_MIN_DAYS  {{ password_passmindays }}' }
      - { search: 'PASS_MIN_LEN', replace: 'PASS_MIN_LEN  {{ password_passminlen }}' }
      - { search: 'PASS_WARN_AGE', replace: 'PASS_WARN_AGE  {{ password_passwarnage }}' }



##########

- name: Enforce password history for pam

#- name: Enforce Password History
#  pamd:
#    name: 'system-auth'
#    type: password
#    control: sufficient 
#    module_path: pam_unix.so
#    module_arguments:
#     - 'remember={{ remember }}'
#    state: args_present
