---
# tasks file for swap

- name: Manage swap files
  block:
    - name: Create swap file
      ansible.builtin.command:
        cmd: dd if=/dev/zero of={{ item.path }} bs=1048576 count={{ item.size }}
        creates: "{{ item.path }}"
      loop: "{{ swap_files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Set permissions on swap file
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: root
        group: root
        mode: "600"
      loop: "{{ swap_files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Create swap file system
      community.general.filesystem:
        fstype: swap
        dev: "{{ item.path }}"
      loop: "{{ swap_files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Mount swap
      ansible.posix.mount:
        path: none
        src: "{{ item.path }}"
        fstype: swap
        opts: sw
        passno: "0"
        dump: "0"
        state: present
      loop: "{{ swap_files }}"
      loop_control:
        label: "{{ item.path }}"
  when:
    - swap_files is defined
    - swap_files | length > 0
    - swap_enabled
  notify:
    - Run swapon

- name: Disable swap
  block:
    - name: Run swapoff
      ansible.builtin.command:
        cmd: swapoff --all
      when:
        - ansible_swaptotal_mb > 0
      notify:
        - Gather facts
      changed_when: true

    - name: Remove swap from fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        state: absent
  when:
    - not swap_enabled
