---
# defaults file for ntp

ntp_packages:
  - chrony
  - tzdata
  - util-linux

ntp_conf: chrony.conf

ntp_interfaces:
  - address: "127.0.0.1"

ntp_pool:
  - name: "0.pool.ntp.org iburst"
  - name: "1.pool.ntp.org iburst"
  - name: "2.pool.ntp.org iburst"

ntp_timezone: America/Colorado/Denver

ntp_log_dir: /var/log/chrony
