---
# tasks file for dotfiles

- name: Ensure git is installed
  ansible.builtin.package:
    name: git
    state: present

- name: Ensure config directory exists
  ansible.builtin.file:
    path: "/home/{{ user }}/.config"
    state: present
  loop:

- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: https://github.com/itscturner/dotfiles.git
    dest: "/home/{{ user }}/.config"
  loop: "{{ users }}"

- name: Set permissions for config directory
  ansible.builtin.file:
    path: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: "{{ user }}"
  loop: "{{ users }}"
