---
# tasks file for systemd

- name: Set default target
  ansible.builtin.file:
    src: "{{ systemd_path }}/{{ systemd_target }}"
    dest: /etc/systemd/system/default.target
    state: link
    mode: '0644'

- name: Include coredump.yml
  ansible.builtin.include_tasks:
    file: coredump.yml

- name: Include journald.yml
  ansible.builtin.include_tasks:
    file: journald.yml

- name: Include logind.yml
  ansible.builtin.include_tasks:
    file: logind.yml

- name: Include user.yml
  ansible.builtin.include_tasks:
    file: user.yml
