---
# tasks file for vscode

- name: Include apt.yml
  ansible.builtin.include_tasks:
    file: apt.yml
  when:
    - ansible_pkg_mgr in [ "apt" ]

- name: Include dnf.yml
  ansible.builtin.include_tasks:
    file: dnf.yml
  when:
    - ansible_pkg_mgr in [ "dnf", "dnf5", "yum" ]

- name: Install VSCode
  ansible.builtin.package:
    name: code
    state: present

- name: Install VSCode extensions
  ansible.builtin.shell:
    cmd: "code --install-extension {{ item }}"
  with_items: "{{ vscode_extensions }}"
  changed_when: "'already installed' not in result.stdout"
  
