---
# tasks file for cron

- name: Ensure cron packages are installed
  ansible.builtin.package:
    name: "{{ cron_packages }}"
    state: present

- name: Start and enable cron
  ansible.builtin.service:
    name: "{{ cron_service }}"
    state: started
    enabled: true
  when:
    - cron_service is defined
    - cron_service | length

- name: Schedule requested cron jobs
  ansible.builtin.cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    job: "{{ item.job }}"
    state: "{{ item.state | default('present') }}"
    user: "{{ item.user | default(omit) }}"
  loop: "{{ cron_jobs }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - cron_jobs is defined

  
