---
# tasks file for logrotate

- name: Install logrotate package
  ansible.builtin.package:
    name: '{{ logrotate_package }}'
    state: present

- name: Template logrotate configuration file
  ansible.builtin.template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: 0644

- name: Generate logrotate.d files
  ansible.builtin.template:
    src: entry.j2
    dest: "{{ logrotate_directory }}/{{ item.name }}"
    mode: 0644
  loop: "{{ logrotate_entries }}"
  when:
    - logrotate_entries is defined
    - item.state is not defined or item.state != "absent"
  loop_control:
    label: "{{ item.name }}"

- name: Remove logrotate.d files
  ansible.builtin.file:
    path: "{{ logrotate_directory }}/{{ item.name }}"
    state: absent
  loop: "{{ logrotate_entries }}"
  when:
    - logrotate_entries is defined
    - item.state is defined
    - item.state == "absent"
  loop_control:
    label: "{{ item.name }}"

- name: Start and enable logrotate
  ansible.builtin.service:
    name: "{{ logrotate_service }}"
    state: started
    enabled: true
