---
# defaults file for kickstart

#
kickstart_file: /tmp/kickstart.ks

#
#kickstart_install_log:

#
kickstart_language: en_US

#
kickstart_keyboard: us

#
kickstart_timezone: 'America/Denver'
kickstart_utc: true

#
kickstart_rootpw:

#
kickstart_reboot: true

#
#kickstart_text:
kickstart_text_noninteractive: true

#
kickstart_url: https://1.2.3.4

#
kickstart_reqpart:

#
kickstart_bootloader:

#
kickstart_bootproto:

#
kickstart_firstboot: disable

#
kickstart_selinux: permissive

# Kickstart Firewall - Enabled or Disabled
kickstart_firewall: disabled



#
kickstart_preinstall_log: /root/kickstart_preinstall.log

#
kickstart_pre:

#
kickstart_postinstall_log: /root/kickstart_postinstall.log

#
kickstart_post:




#
# Workstation Packages:
kickstart_packages:
  - @^workstation-product-environment
  - @gnome-desktop
  - @remote-desktop-clients
  - ansible
  - gnome-backgrounds
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-auto-move-windows
  - gnome-shell-extension-dash-to-dock
  - gnome-shell-extension-desktop-icons
  - gnome-shell-extension-drive-menu
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-native-window-placement
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-screenshot-window-sizer
  - gnome-shell-extension-user-theme
  - gnome-shell-extension-window-list
  - gnome-shell-extension-windowsNavigator
  - gnome-shell-extension-workspace-indicator
  - tigervnc








##########

kickstart_target: graphical




kickstart_timesource:

kickstart_bootloader:

kickstart_clearpart: ''

kickstart_masterbootrecord:

kickstart_partitions:
  - 

kickstart_logical_volumes:
  -

kickstart_volume_groups:
  -

kickstart_services:
  - sshd

kickstart_firewall: "firewall --enabled --ssh"

kickstart_selinux: "selinux --enforcing"

kickstart_authselect: ''

kickstart_packages:
  - 

