---
# tasks file for pip - assert

- name: assert | Verify pip_python_version
  ansible.builtin.assert:
    that:
      - pip_python_version is float
      - pip_python_version is not none
    quiet: true
  when: pip_python_version is defined

- name: assert | Verify pip_executable
  ansible.builtin.assert:
    that:
      - pip_executable is string
      - pip_executable is not none
    quiet: true
  when: pip_executable is defined

- name: assert | Verify pip_conf_index_url
  ansible.builtin.assert:
    that:
      - pip_conf_index_url is string
      - pip_conf_index_url is not none
    fail_msg: "Pip Index URL variable is required."
    quiet: true
