---
# tasks file for pip - assert

- name: assert | Verify Pip Python version
  ansible.builtin.assert:
    that:
      - pip_python_version is float
      - pip_python_version is not none
    fail_msg: "Pip Python version variable (pip_python_version) is required."
    quiet: true
