---
# defaults file for ansible


#
ansible_install: # package / pip



#
ansible_venv:
ansible_venv_path:


#
ansible_dependencies:
  - python3
  - python3-pip

#
ansible_pip_packages:
  - ansible-core
  - ansible-dev-tools
  - ansible-sign
  - molecule
  - paramiko
  - pytest-testinfra



#
ansible_collection_path:

#
ansible_collections:
  - ansible.posix
  - ansible.utils
  - community.general
  - kubernetes.core


