---
# tasks file for diskspace

- name: Include mount.yml
  ansible.builtin.include_tasks:
    file: mount.yml
  loop: "{{ diskspace_mounts }}"
  loop_control:
    label: "{{ mount.name }}"
    loop_var: mount
