---
# tasks file for backup

- name: Create remote backup directory
  ansible.builtin.file:
    path:
    state: directory
    mode: 0777

- name: Create backup directory
  ansible.builtin.file:
    path:
    state: directory
    mode: 0750
  connection: local
  become: false

- name: Backup objects listed in backup_objects
  ansible.builtin.include_tasks:
    file: backup_objects.yml
  loop: "{{ backup_objects }}"
  loop_control:
    loop_var: object
  when:
    - backup_objects is defined
