---
# defaults file for pip

# Required packages to install for pip.
pip_required_packages:
  - "python{{ pip_python_version }}"
  - "python{{ pip_python_version }}-pip"
  - "python{{ pip_python_version }}-setuptools"

# Default Python version.
pip_python_version: '3.12'

# Pip executable path. Changes depending on the 'pip_python_version' variable.
pip_executable: "/usr/bin/pip{{ pip_python_version }}"

# Default timeout value in seconds.
pip_conf_timeout: 60

# Location of the pip log file.
pip_conf_log_file:

# Only install pip packages in a virtual environment.
pip_conf_respect_virtualenv: true

# Download cache location for pip.
pip_conf_download_cache:

# Level of verbosity for pip output.
pip_conf_verbose:

# Trust a specific host if it doesn't use SSL/TLS.
pip_conf_trusted_host:

# Set the primary pip package index.
pip_conf_index_url:

# Proxy information for pip.
pip_conf_proxy:

# Add an additional pip package index to search if the primary fails.
pip_conf_extra_index_url:

# Where pip should look for packages to install.
pip_conf_find_links: 

# Ignore already installed packages.
pip_conf_ignore_installed: true

# Always use the '--no-cache-dir' flag for pip installations.
pip_conf_no_cache_dir: true
 
# Format to display 'pip list' in.
pip_conf_list_format: columns

# Extra configurations to add to the pip configuration file. (Section, Option, Value).
pip_extra_configurations: []
