---
galaxy_info:
  author: itscturner
  description: An ansible role to configure system backups.
  license: Apache-2.0
  min_ansible_version: "2.12"

  platforms:
    - name: RHEL
      versions:
        - "9"

  galaxy_tags:
    - backup
    - storage
    - system

  dependencies: []
