---
galaxy_info:
  author: itscturner
  role_name: usbguard
  description: An ansible role to install and configure USBGuard.
  license: Apache-2.0
  min_ansible_version: "2.12"

  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - security
    - system
    - usbguard

  dependencies: []
