---
galaxy_info:
  author: itscturner
  role_name: scripts
  description: An ansible role to place scripts on your system.
  license: Apache-2.0
  min_ansible_version: "2.12"

  platforms:
    - name: RHEL
      versions:
        - "9"

  galaxy_tags:
    - scripts
    - system

  dependencies: []
