galaxy_info:
  author: itscturner
  role_name: facts
  description: An ansible role for creating custom facts.
  license: Apache-2.0
  min_ansible_version: "2.12"

  platforms:
    - name: Debian
      versions:
        - all
    - name: RHEL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - facts
    - system

  dependencies: []
