---
galaxy_info:
  author: itscturner
  role_name: users
  description: An Ansible role to manage users.
  license: Apache-2.0
  min_ansible_version: "2.12"

  platforms:
    - name: EL
      versions:
        - all

  galaxy_tags:
    - system
    - user
    - users

  dependencies: []
