galaxy_info:
  author: itscturner
  description: An ansible role to configure logrotate.
  license:
  min_ansible_version:

  galaxy_tags:
    - logrotate
    - logs
    - monitoring
    - system

  dependencies: []
