---
# tasks file for kubectl

- name: Install kubectl
  ansible.builtin.get_url:
    url: "{{ kubectl_url }}"
    dest: /usr/bin/kubectl
    mode: 0755
    validate_certs: "{{ kubectl_validate_certs }}"
