---
# tasks file for kubectl

- name: Install kubectl
  ansible.builtin.get_url:
    url: "{{ kubectl_url }}"
    dest: "{{ kubectl_bin_path }}"
    mode: 0755
    validate_certs: "{{ kubectl_validate_certs }}"
