---
galaxy_info:
  author: itscturner
  role_name: sshd
  description: An ansible role to configure sshd.
  license: Apache-2.0
  min_ansible_version: "2.12"

  platforms:
    - name: RHEL
      versions:
        - "9"

  galaxy_tags:
    - ssh
    - sshd
    - system

  dependencies: []
