---
# defaults file for software

# A list of software packages to manage.
# software_packages:
#   - name: firefox
#   - name: vim-enhanced
#     state: latest
#   - name: tcpdump
#     state: absent

software_packages: []
