---
# tasks file for git - assert

- name: assert | Verify Git Repository destination variable
  ansible.builtin.assert:
    that:
      - git_repository_destination is defined
      - git_repository_destination is string
      - git_repository_destination is not none
    quiet: true
    fail_msg: "Git Repository destination variable (git_repository_destination) is not defined, or is not valid."

- name: assert | Verify Git Repositories variable
  ansible.builtin.assert:
    that:
      - git_repositories is iterable
    quiet: true
    fail_msg: "Git Repositories variable (git_repositories) is not valid."
  when:
    - git_repositories is defined

- name: assert | Verify values in Git Repositories variable
  ansible.builtin.assert:
    that:
      - item.repository is defined
      - item.repository is string
      - item.repository is not none
      - item.destination is defined
      - item.destination is string
      - item.destination is not none
    quiet: true
    fail_msg: "Values in Git Repositories variable (git_repositories) are not valid."
  loop: "{{ git_repositories }}"
  loop_control:
    label: "{{ item.repository }}"
  when:
    - git_repositories is defined
