---
# tasks file for git

- name: Install git
  ansible.builtin.dnf:
    name: "{{ git_packages }}"
    state: present

- name: Template git configuration file
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "/home/{{ username }}/.gitconfig"
    mode: 0644
  when:
    - git_user_name is defined
    - git_user_email is defined
    - git_username is defined
