---
# tasks file for git

- name: Install git
  ansible.builtin.dnf:
    name: "{{ git_packages }}"
    state: present

- name: Template git configuration file
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "/home/{{ system_username }}/.gitconfig"
    mode: 0644
  with_items: "{{ git_users }}"
