---
# tasks file for git

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install Git packages
  ansible.builtin.package:
    name: "{{ git_packages }}"
    state: present

- name: Ensure the specified user exists
  ansible.builtin.getent:
    database: passwd
    key: "{{ git_user }}"
    fail_key: false

- name: Ensure user's home directory exists
  ansible.builtin.file:
    path: "/home/{{ git_user }}"
    state: directory
    owner: "{{ git_user | default(omit) }}"
    group: "{{ git_group | default(omit) }}"
    mode: "0755"

- name: Template Git configuration file
  ansible.builtin.template:
    src: gitconfig.j2
    dest: /home/{{ git_user }}/.gitconfig
    mode: "0644"
  when:
    - git_user_email is defined
    - git_user_name is defined

- name: Create Git repository destination
  ansible.builtin.file:
    path: "{{ git_repository_destination }}"
    state: directory
    owner: "{{ git_user | default(omit) }}"
    group: "{{ git_group | default(omit) }}"
    mode: "0750"
  when:
    - git_repository_destination is defined
