---
galaxy_info:
  author: itscturner
  role_name: password
  description: An ansible role to configure password policies.
  license: Apache-2.0
  min_ansible_version: "2.12"

  platforms:
    - name: RHEL
      versions:
        - "9"

  galaxy_tags:
    - password
    - security
    - system

  dependencies: []
