---
galaxy_info:
  author: cturner
  role_name: software
  description: "An ansible role to install or uninstall software on your system."
  license: Apache-2.0

  galaxy_tags:
    - software
    - system

dependencies: []
