---
# tasks file for umask

- name: Set umask for users
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "umask {{ umask }}"
    regexp: '^umask\s+\d+'
    create: true
    mode: 0644
  become: true
  become_user: "{{ item }}"
  loop: "{{ umask_users }}"
