---
# tasks file for users

- name: Loop over users_groups
  ansible.builtin.include_tasks:
    file: group.yml
  loop: "{{ users_groups }}"
  loop_control:
    label: "{{ group.name }}"
    loop_var: group
  when:
    - users_groups is defined

- name: Ensure the /etc/sudoers.d directory is included
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "{{ users_sudo_includedir }}"
    regexp: "^(@|#)includedir"
    validate: "visudo --check --file %s"

- name: Loop over users
  ansible.builtin.include_tasks:
    file: user.yml
  loop: "{{ users }}"
  loop_control:
    label: "{{ user.name }}"
    loop_var: user
  when:
    - users is defined
