---
# defaults file for storage

# Required packages for the storage role.
storage_required_packages:
  - e2fsprogs
  - lvm2
  - parted
  - xfsprogs

# Default options for Volume Groups.
storage_volume_group_default_options: '--zero y'

# Default Filesystem type.
storage_default_fstype: ext4

# Partitions to configure.
# Name, Number, Flags (defaults to 'omit'), Partition Start (defaults to 'omit'), Partition End (defaults to 'omit'), Label (defaults to 'omit').
storage_partition: []
#  - name:
#    number:
#    flags:
#    partition_start:
#    partition_end:
#    label:

# Volume Groups to configure.
# Name, Devices, Size (defaults to 'omit'), Options (defaults to 'storage_volume_group_default_options').
storage_volume_group: []
#  - name:
#    devices:
#       -
#    size:
#    options:

# Volumes to configure.
# Name, VG, Size, Options (defaults to 'omit').
storage_volume: []
#  - name:
#    vg:
#    size:
#    options:

# Filesystems to configure.
# Name, FSType (defaults to 'storage_default_fstype').
storage_filesystem: []
#  - name:
#    fstype:

# Mounts to configure.
# Name, Source, FSType (defaults to 'storage_default_fstype'), Options (defaults to 'omit'), Boot (defaults to 'omit'), Dump (defaults to 'omit'), PassNo (defaults to 'omit'), Owner (defaults to 'omit'), Group (defaults to 'omit'), Mode (defaults to 'omit').
storage_mount: []
#  - name:
#    source:
#    fstype:
#    options:
#    boot:
#    dump:
#    passno:
#    owner:
#    group:
#    mode:
