---

- name: packages | Template pacman.conf
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - packages

- name: packages | Install pacman packages
  community.general.pacman:
    name: "{{ pacman_packages }}"
    state: present

- name: packages | Update pacman packages
  community.general.pacman:
    upgrade: true
    update_cache: true

- name: packages | Install aur packages


- name: packages | Install fonts
