---
# tasks file for ansible

- name: Include install.yml
  ansible.builtin.include_tasks:
    file: install.yml

- name: Ensure ansible directory exists
  ansible.builtin.file:
    path: "{{ ansible_configuration_directory }}"
    state: directory
    mode: 0755

- name: Configure ansible
  ansible.builtin.template:
    src: "{{ ansible_config_file }}.j2"
    dest: "{{ ansible_configuration_directory }}/{{ ansible_config_file }}"
    mode: 0644
