---
# tasks file for ansible

- name: Install ansible packages
  ansible.builtin.dnf:
    name: "{{ ansible_packages }}"
    state: present

- name: Install ansible collections
  ansible.builtin.shell:
    cmd: "ansible-galaxy collection install {{ ansible_collections }}"

- name: Ensure ansible directory exists
  ansible.builtin.file:
    path: "{{ ansible_configuration_directory }}"
    state: directory
    mode: 0755

- name: Configure ansible
  ansible.builtin.template:
    src: "{{ ansible_config_file }}.j2"
    dest: "{{ ansible_configuration_directory }}/{{ ansible_config_file }}"
    mode: 0644
