---
# tasks file for sudo

- name: Ensure sudo package is installed - Debian
  ansible.builtin.apt:
    name: "{{ sudo_packages }}"
    state: present
    install_recommends: true
  when: ansible_os_family == 'Debian'

- name: Ensure sudo package is installed - RedHat
  ansible.builtin.dnf:
    name: "{{ sudo_packages }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Configure sudoers file
  ansible.builtin.template:
    src: sudoers.j2
    dest: "{{ sudo_sudoers_file }}"
    owner: root
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -cf %s
