---
# tasks file for sudo

- name: Ensure sudo package is installed
  ansible.builtin.dnf:
    name: "{{ sudo_package }}"
    state: present


- name: Configure sudoers file
  ansible.builtin.template:
    src: sudoers.j2
    dest: "{{ sudo_sudoers_file }}"
    owner: root
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -cf %s

- name: Configure sudoers.d files
  ansible.builtin.template:
    src:
    dest:
    owner:
    group:
    mode:
    validate: /usr/sbin/visudo -cf %s
  with_items: "{{ sudo_sudoersd_files }}"

