---
# defaults file for go

# Verion of Go to install.
go_version: "1.17.6"

# Where to place Go.
go_destination: /usr/local

# Where to download packages to, aka GOROOT.
go_path: /root/go

##########

# Go language SDK version number
golang_version: '1.24.2'

# Mirror to download the Go language SDK redistributable package from
golang_mirror: 'https://storage.googleapis.com/golang'

# Base installation directory the Go language SDK distribution
golang_install_dir: '/opt/go/{{ golang_version }}'

# Directory to store files downloaded for Go language SDK installation
golang_download_dir: "{{ x_ansible_download_dir | default(ansible_facts.env.HOME + '/.ansible/tmp/downloads') }}"

# Location for GOPATH environment variable
golang_gopath:
