---
galaxy_info:
  author: itscturner
  role_name: aide
  description: An ansible role to install and configure aide.
  license: Apache-2.0
  min_ansible_version: "2.12"

  platforms:
    - name: RHEL
      versions:
        - "9"

  galaxy_tags:
    - aide
    - monitoring
    - system

  dependencies: []
