---
galaxy_info:
  author: itscturner
  role_name: repos
  description: An ansible role to configure repos.
  license: Apache-2.0
  min_ansible_version: "2.12"

  platforms:
    - name: RHEL
      versions:
        - "9"

  galaxy_tags:
    - dnf
    - packages
    - repos
    - rpm

  dependencies: []
