# Tasks file for fips

- name: Install crypto-policies-scripts
  ansible.builtin.package:
    name: crypto-policies-scripts

- name: Retrieve FIPS mode
  ansible.builtin.command:
    cmd: /usr/bin/fips-mode-setup --is-enabled
  register: fips_mode
  changed_when: false
  failed_when:
    - fips_mode.rc not in fips_exit_codes
  
- name: Enable FIPS mode
  ansible.builtin.command:
    cmd: /usr/bin/fips-mode-setup --enable
  changed_when: false
  when:
    - fips_mode.rc == fips_disabled_code
  notify:
    - Get default kernel
    - Update default kernel arguments

- name: Get crypto policy
  ansible.builtin.command:
    cmd: update-crypto-policies --show
  register: fips_current_crypto_policy
  changed_when: false

- name: Set crypto policy
  ansible.builtin.command:
    cmd: update-crypto-policies --set {{ fips_policy }}
  changed_when: false
  when:
    - fips_current_crypto_policy.stdout != fips_policy
