---
# tasks file for usbguard

- name: Install usbguard
  ansible.builtin.dnf:
    name: usbguard
    state: present

- name: Stat USB device directory
  ansible.builtin.stat:
    path: /sys/bus/usb/devices
  register: usb_devices

- name: Start and enable usbguard
  ansible.builtin.service:
    name: usbguard
    state: started
    enabled: true

- name: Generate usbguard policy
  ansible.builtin.shell:
    cmd: "usbguard generate-policy > /etc/usbguard/rules.conf"



