---
argument_specs:
  main:
    short_description: "An Ansible role to install and configure Git."
    description: >
      An Ansible role to install and configure Git.
    author: itscturner
    options:
      git_user:
        required: true
        default: null
        description: User's system username to configure Git.
        type: str
      git_group:
        required: true
        default: null
        description: User's system group to configure Git.
        type: str
