---
argument_specs:
  main:
    short_description: "An Ansible role to install and configure Git."
    description: >
      An Ansible role to install and configure Git.
    author: itscturner
    options:
      git_user_email:
        required: true
        default: null
        description: User's email to configure Git.
        type: str
      git_user_name:
        required: true
        default: null
        description: User's name to configure Git.
        type: str
