---
# tasks file for httpd

- name: Install httpd packages
  ansible.builtin.dnf:
    name: "{{ httpd_packages }}"
    state: present

- name: Configure httpd
  ansible.builtin.template:
    src: httpd.conf.j2
    dest: "{{ httpd_directory }}/conf/httpd.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - Test httpd configuration
    - Restart httpd

- name: Import ssl.yml
  ansible.builtin.import_tasks:
    file: ssl.yml
  when:
    - https_ssl_enabled

- name: Import locations.yml
  ansible.builtin.import_tasks:
    file: locations.yml
  when:
    - httpd_locations is defined

- name: Import vhosts.yml
  ansible.builtin.import_tasks:
    file: vhosts.yml
  when:
    - httpd_vhosts is defined

- name: Import directories.yml
  ansible.builtin.import_tasks:
    file: directories.yml
  when:
    - httpd_directories is defined

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Remove default html
  ansible.builtin.file:
    path: "{{ httpd_data_directory }}/index.html"
    state: absent
  when:
    - httpd_remove_default_index

- name: Start and enable httpd
  ansible.builtin.service:
    name: "{{ httpd_service }}"
    state: started
    enabled: true
