---
# defaults file for epel

# EPEL repo file path.
epel_repofile: /etc/yum.repos.d/epel.repo

# EPEL repo GPG key.
epel_repo_gpg_key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"

# EPEL repo URL.
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
