---
# tasks file for storage - assert

- name: assert | Verify Partition variable
  ansible.builtin.assert:
    that:
      - storage_partition.name is defined
      - storage_partition.number is defined
      - storage_partition.partition_start is defined or partition.part_end is defined
    fail_msg: "Partition variable is not defined or is not valid."
    quiet: true

- name: assert | Verify Partition Label variable
  ansible.builtin.assert:
    that:
      - storage_partition.label is defined
      - storage_partition.label is iterable
      - storage_partition.label in [ "aix", "amiga", "bsd", "dvh", "gpt", "loop", "mac", "msdos", "pc98", "sun" ]
    fail_msg: "Partition Label variable is not defined or is not valid."
    quiet: true
  when:
    - storage_partition.label is defined

- name: assert | Verify Volume Group variable
  ansible.builtin.assert:
    that:
      - storage_volume_group.name is defined
      - storage_volume_group.devices is defined
    fail_msg: "Volume Group variable is not defined."
    quiet: true

- name: assert | Verify Volume variable
  ansible.builtin.assert:
    that:
      - storage_volume.name is defined
      - storage_volume.vg is defined
      - storage_volume.size is defined
    fail_msg: "Volume variable is not defined."
    quiet: true

- name: assert | Verify Filesystem variable
  ansible.builtin.assert:
    that:
      - storage_filesystem.name is defined
    fail_msg: "Filesystem variable is not defined."
    quiet: true

- name: assert | Verify Mount variable
  ansible.builtin.assert:
    that:
      - storage_mount.name is defined
      - storage_mount.source is defined
    fail_msg: "Mount variable is not defined."
    quiet: true
