---
# tasks file for storage - filesystem

- name: filesystem | Create Filesystem
  community.general.filesystem:
    dev: "{{ filesystem.name }}"
    fstype: "{{ filesystem.fstype | default(storage_default_fstype) }}"
  notify:
    - Reload systemd

- name: filesystem | Run handlers
  ansible.builtin.meta: flush_handlers
