---
# tasks file for storage - mount

- name: mount | Create Mountpoint
  ansible.builtin.file:
    path: "{{ storage_mount.name }}"
    state: directory
    owner: "{{ storage_mount.owner | default(omit) }}"
    group: "{{ storage_mount.group | default(omit) }}"
    mode: "{{ storage_mount.mode | default(omit) }}"

- name: mount | Add Mount to fstab
  ansible.posix.mount:
    path: "{{ storage_mount.name }}"
    src: "{{ storage_mount.source }}"
    state: present
    fstype: "{{ storage_mount.fstype | default(storage_default_fstype) }}"
    opts: "{{ storage_mount.options | default(omit) }}"
    boot: "{{ storage_mount.boot | default(omit) }}"
    dump: "{{ storage_mount.dump | default(omit) }}"
    passno: "{{ storage_mount.passno | default(omit) }}"

- name: mount | Reload Systemd
  ansible.builtin.command:
    cmd: systemctl daemon-reload # noqa: command-instead-of-module
  changed_when: false
  when:
    - ansible_service_mgr == "systemd"

- name: mount | Mount Filessytem
  ansible.posix.mount:
    path: "{{ storage_mount.name }}"
    src: "{{ storage_mount.source }}"
    state: mounted
    fstype: "{{ storage_mount.fstype | default(storage_default_fstype) }}"
    opts: "{{ storage_mount.options | default(omit) }}"
    boot: "{{ storage_mount.boot | default(omit) }}"
    dump: "{{ storage_mount.dump | default(omit) }}"
    passno: "{{ mount.passno | default(omit) }}"
  notify:
    - Refresh facts
