---
# tasks file for storage - partition

- name: partition | Create Partition
  community.general.parted:
    device: "{{ storage_partition.name }}"
    number: "{{ storage_partition.number }}"
    flags: "{{ storage_partition.flags | default(omit) }}"
    part_start: "{{ storage_partition.partition_start | default(omit) }}"
    part_end: "{{ storage_partition.partition_end | default(omit) }}"
    label: "{{ storage_partition.label | default(omit) }}"
    state: present
