---
# tasks file for storage - volume group

- name: volume_group | Create Volume Groups
  community.general.lvg:
    vg: "{{ volumegroup.name }}"
    pvs: "{{ volumegroup.devices | join(',') }}"
    pesize: "{{ volumegroup.size | default(omit) }}"
    vg_options: --zero y
