---
# tasks file for storage - volume

- name: volume | Create Logical Volume
  community.general.lvol:
    lv: "{{ storage_volume.name }}"
    vg: "{{ storage_volume.vg }}"
    size: "{{ storage_volume.size }}"
    opts: "{{ storage_volume.opts | default(omit) }}"
  notify:
    - Run vgscan

- name: volume | Run handlers
  ansible.builtin.meta: flush_handlers
