---
# tasks file for storage - volume group

- name: volume_group | Create Volume Group
  community.general.lvg:
    vg: "{{ storage_volume_group.name }}"
    pvs: "{{ storage_volume_group.devices | join(',') }}"
    pesize: "{{ storage_volume_group.size | default(omit) }}"
    vg_options: "{{ storage_volume_group.options | default(storage_volume_group_default_options) }}"
