---
# tasks file for alternatives

- name: Ensure alternatives packages are installed
  ansible.builtin.package:
    name: "{{ alternatives_packages }}"
    state: present

- name: Configure alternatives
  community.general.alternatives:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
    link: "{{ item.link }}"
  loop: "{{ alternatives_list }}"
  loop_control: "{{ item.name }}"
  when:
    - alternatives_list is defined
