---
# tasks file for alternatives

- name: Install alternatives packages
  ansible.builtin.package:
    name: "{{ alternatives_packages }}"
    state: present

- name: Configure alternatives
  community.general.alternatives:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
    link: "{{ item.link }}"
  loop: "{{ alternatives }}"
  loop_control: "{{ item.name }}"
  when:
    - alternatives is defined
