---
# tasks file for facts - assert

- name: assert | Test facts variable
  ansible.builtin.assert:
    that:
      - facts is iterable
    quiet: true
    fail_msg: "Facts variable (facts) is not valid."
  when:
    - facts is defined

- name: assert | Test item in facts
  ansible.builtin.assert:
    that:
      - item.key is defined
      - item.key is string
      - item.key is not none
      - item.value is defined
    quiet: true
    fail_msg: "Values of Facts variable (facts) are not valid."
  loop: "{{ facts }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - facts is defined
