---
galaxy_info:
  author: itscturner
  role_name: helm
  description: An ansible role to install and configure helm.
  license: Apache-2.0
  min_ansible_version: "2.12"

  platforms:
    - name: RHEL
      versions:
        - "9"

  galaxy_tags:
    - helm
    - packages
    - system

  dependencies: []
