---
# defaults file for password



#password_expiration_file: /etc/login.defs


password_complexity_file: /etc/security/pwquality.conf



# Password complexity.
minlen: 12
lcredit: -1
ucredit: -1
dcredit: -1
ocredit: -1

# Password history.
remember: 12

# Password expiration.
PASS_MAX_DAYS: 99999
PASS_MIN_DAYS: 0
PASS_MIN_LEN: 12
PASS_WARN_AGE: 7



# pwquality.conf
#
password_difok: 1

#
password_minlen: 8

#
password_dcredit: 0

#
password_ucredit: 0

#
password_ocredit: 0

#
password_minclass: 0

#
password_maxrepeat: 0

#
password_maxclassrepeat: 0

#
password_gecoscheck: 0

#
password_dictcheck: 1

#
password_usercheck: 1

#
password_usersubstr: 0

#
password_enforcing: 1

#
password_dictpath:

#
password_retry: 3

#
password_enforceforroot: true

#
password_localusersonly: true



















