---
# tasks file for sshd

- name: Ensure sshd packages are installed
  ansible.builtin.package:
    name: "{{ sshd_packages }}"
    state: present

- name: Configure sshd
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ sshd_config_directory }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ sshd_config_files }}"
  notify:
    - Test sshd configuration
    - Restart sshd

- name: Start and enable sshd
  ansible.builtin.service:
    name: "{{ sshd_service }}"
    state: started
    enabled: true
